version: '3'

services:
  api:
    build: ./api
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    env_file:
      - ./api/.env
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
  
  app:
    build: ./app
    command: npm run start-watch
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./app:/app
      - /Users/csamin/Documents/Patho/app/node_modules/
    stdin_open: true
    tty: true